### ISSUE TITLE
GetCurrentLocation doesn't work on Android

### ISSUE THREAD

**Issue by Mariam-K-code-care** [Agontuk/react-native-geolocation-service#324] opened 2021-12-13 06:55 UTC
Hello, the issue is the same as [here](https://github.com/react-native-geolocation/react-native-geolocation/issues/119), was wondering if there are any solutions on this repo for this

**Comment by mashad6** [comment] 2022-01-03 08:04
Having same problem, any solution on this?

**Comment by CoryBall** [comment] 2022-01-06 07:17
I was having the same problem, and the issue was I had a process similar to: 
```
let tryLocation: GeoPosition | undefined = undefined;

Geolocation.getCurrentPosition(
  (position: GeoPosition) => {
    tryLocation = position;
  },
  (error: GeoError) => {
    console.error(error);
  },
  {
    accuracy: {
      android: 'high',
      ios: 'best',
    },
    enableHighAccuracy: true,
    timeout: 1000 * 60 * 2,
    maximumAge: 1000 * 10,
    distanceFilter: 0,
  } as GeoOptions,
);

if (!tryLocation) {
  return;
}

const location = tryLocation as GeoPosition;
```

and the issue was that it was just continuing through the `Geolocation.getCurrentPosition` function and not hitting a callback before moving on to when I used `location`

I wrapped the function in a promise and it is working as expected now. Try it out
```
export async function getCurrentLocation(): Promise<GeoPosition | undefined> {
  const hasPermission = await hasLocationPermission();

  if (!hasPermission) {
    return;
  }
  return new Promise(resolve => {
    Geolocation.getCurrentPosition(
      (position: GeoPosition) => {
        resolve(position);
        return position;
      },
      (geoError: GeoError) => {
        console.error(geoError);
        return;
      },
      {
        accuracy: {
          android: 'high',
          ios: 'best',
        },
        timeout: 1000 * 4,
        maximumAge: 1000 * 10,
        distanceFilter: 0,
      } as GeoOptions,
    );
  });
}
```

**Comment by Agontuk** [comment] 2022-05-27 12:22
> ```
> const hasPermission = await hasLocationPermission();
> 
> if (!hasPermission) {
>   return;
> }
> 
> let tryLocation: GeoPosition | undefined = undefined;
> 
> Geolocation.getCurrentPosition(
>   (position: GeoPosition) => {
>     tryLocation = position;
>   },
>   (error: GeoError) => {
>     console.error(error);
>   },
>   {
>     accuracy: {
>       android: 'high',
>       ios: 'best',
>     },
>     enableHighAccuracy: true,
>     timeout: 1000 * 60 * 2,
>     maximumAge: 1000 * 10,
>     distanceFilter: 0,
>   } as GeoOptions,
> );
> 
> if (!tryLocation) {
>   return;
> }
> 
> const location = tryLocation as GeoPosition;
> ```

This'll not work because `getCurrentPosition` is an async method. You're synchronously declaring variable `location` before the method returning any result.


Closing this as there's no sample repo to reproduce this.

**Closed by Agontuk** 2022-05-27 12:22 UTC
Labels: bug
