### ISSUE TITLE
How do i handle this error?

### ISSUE THREAD

**Issue by kamalpandey** [Agontuk/react-native-geolocation-service#302] opened 2021-08-21 16:13 UTC
ERROR  Invariant Violation: No callback found with cbID 32337 and callID 16168 for  RNFusedLocation.getCurrentPosition - most likely the callback was already invoked. Args: '[{"message":"Location request timed out.","code":3}]'

**Comment by Agontuk** [comment] 2021-08-28 09:46
which library version are you using ?

**Comment by kamalpandey** [comment] 2021-08-28 13:28
@Agontuk I am using version v5.3.0-beta.1

**Comment by efstathiosntonas** [comment] 2021-08-30 08:50
I got the same error from time to time.

trace from bugsnag:

```
java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
        at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:26)
        at com.agontuk.RNFusedLocation.RNFusedLocationModule$1.onLocationError(RNFusedLocationModule.java:91)
        at com.agontuk.RNFusedLocation.FusedLocationProvider$2.run(FusedLocationProvider.java:70)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:7604)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

```

**Comment by Agontuk** [comment] 2021-08-30 12:59
Is there any way to reproduce this error ? If you can, please share an example project.

**Comment by Agontuk** [comment] 2021-08-30 13:18
One possibility would be that you're calling `getCurrentPosition` inside a loop. Can you share how are you calling it ?
@kamalpandey I think this applies for you too.

**Comment by kamalpandey** [comment] 2021-08-30 13:56
@Agontuk I was using the example provided in repo.

**Comment by Agontuk** [comment] 2021-08-31 14:08
> @Agontuk I was using the example provided in repo.

unable to reproduce this on my end. Provide reproducible steps if you can.

**Comment by kamalpandey** [comment] 2021-09-02 15:09
@Agontuk Sorry it was random. :(

**Comment by Agontuk** [comment] 2021-12-06 18:57
@jhui134 can you provide a sample repo that reproduces this ? Would be very helpful.

**Comment by nes123** [comment] 2022-02-23 13:56
Did you manage to restore it? it happens to us very rarely as well..the scenario is not well understood.

**Comment by ananyosen** [comment] 2022-03-29 09:55
It seems that we've seen this issue before #13 and was fixed then by wrapping the code in try-catch (https://github.com/Agontuk/react-native-geolocation-service/commit/158ebabec9b6c4c049953a21351eea2a6e9243d8). However, the latest code does not have the same try-catch blocks and causing a crash. Can we add the code back? What would break if we were to do that?

**Comment by francois-pasquier** [comment] 2022-03-29 23:11
The issue is hitting me as well: switching between a viro screen and a screen with getCurrentPosition...

Do you have any idea on what could fix it @Agontuk?

**Comment by alfergus0n** [comment] 2022-03-31 21:43
i am also getting this now in android

**Comment by ananyosen** [comment] 2022-04-01 11:31
Raised #338 , has fixed the issue for us.

**Comment by Agontuk** [comment] 2022-04-08 09:59
Hello guys, can you please try the latest changes from master branch ? I rewrote the location change listener logic, hopefully it'll solve the issue.

**Comment by francois-pasquier** [comment] 2022-04-12 08:57
> Hello guys, can you please try the latest changes from master branch ? I rewrote the location change listener logic, hopefully it'll solve the issue.

Actually, I'd like to try it. Could you make it a npm release? 🙏🏽

**Comment by efstathiosntonas** [comment] 2022-04-12 18:46
@francois-pasquier you can try `npm install username/repo#master --save`, same goes with `yarn add`

**Comment by Agontuk** [comment] 2022-06-25 09:43
New version published, closing this.

**Closed by Agontuk** 2022-06-25 09:43 UTC
