### ISSUE TITLE
 2 Location service is turned off in ios

### ISSUE THREAD

**Issue by raghvendra007** [Agontuk/react-native-geolocation-service#248] opened 2021-03-08 09:44 UTC
2 Location service is turned off in  IOS ,Location services is turned off but showing popup for fraction of second and dissappeared

**Comment by Agontuk** [comment] 2021-03-25 16:17
Possible duplicate of #252 , closing this in favor of that issue. Please provide details in that issue thread.

**Closed by Agontuk** 2021-03-25 16:17 UTC
