### ISSUE TITLE
support xcode 13

### ISSUE THREAD

**Issue by maystrenkoYurii** [Agontuk/react-native-geolocation-service#313] opened 2021-09-21 19:34 UTC
i disabled flipper https://github.com/facebook/react-native/issues/31733 but app error build with xcode 13
<img width="826" alt="Снимок экрана 2021-09-21 в 22 31 05" src="https://user-images.githubusercontent.com/23016311/134235827-b4296a7a-d6cb-4836-9b03-e0c5c67b2bf0.png">

**Comment by JZambo9** [comment] 2021-09-22 07:44
I'm having the same issue. Is there anything that can be done from my part to fix it?

**Comment by nithinyell** [comment] 2021-09-22 14:06
> I'm having the same issue. Is there anything that can be done from my part to fix it?

Update to React Native 0.65

**Comment by hanifmhd** [comment] 2021-09-22 15:07
> > I'm having the same issue. Is there anything that can be done from my part to fix it?
> 
> @JZambo9
> 
> Update to React Native 0.65

is it the only solution?

**Comment by temaput** [comment] 2021-09-23 13:14
As a temporary solution, adding empty swift file in XCode worked for me. Take a look here: 
https://github.com/zalando/SwiftMonkey/issues/80#issuecomment-604994492
No need for autogenerating the bridge.h file, just the .swift is enough

**Comment by alexanderblackh** [comment] 2021-09-28 05:15
> As a temporary solution, adding empty swift file in XCode worked for me. Take a look here:
> [zalando/SwiftMonkey#80 (comment)](https://github.com/zalando/SwiftMonkey/issues/80#issuecomment-604994492)
> No need for autogenerating the bridge.h file, just the .swift is enough

This is the actual solution for this error, This can and sometimes will happen on a fresh react native build (Even happened earlier today when debugging issues unrelated to this project).

**Comment by neildevas** [comment] 2021-10-04 18:04
@zalando s solution worked for me. Does this file need to be present to create a working production build?

**Comment by ShaeerN-GO** [comment] 2021-10-15 15:41
the same error here -_- with xcode 13. 
 React-native : 0.65.1

**Comment by Agontuk** [comment] 2021-11-24 17:37
Sorry for the late reply, I'll upgrade to xcode 13 and try to reproduce the issue.

**Comment by Agontuk** [comment] 2021-11-25 18:40
Unable to reproduce this in xcode 13 with RN 0.65, build working fine for me.

> As a temporary solution, adding empty swift file in XCode worked for me. Take a look here: [zalando/SwiftMonkey#80 (comment)](https://github.com/zalando/SwiftMonkey/issues/80#issuecomment-604994492) No need for autogenerating the bridge.h file, just the .swift is enough

This is already described in the setup docs. If you don't do this, build will fail.

**Comment by Agontuk** [comment] 2022-05-27 12:30
Closing this as this is not reproducible, and the solution presented here is already described in the setup section

**Closed by Agontuk** 2022-05-27 12:30 UTC
Labels: bug
